version = 5.1.0
archive_dir = /etc/letsencrypt/archive/geiglobal.org
cert = /etc/letsencrypt/live/geiglobal.org/cert.pem
privkey = /etc/letsencrypt/live/geiglobal.org/privkey.pem
chain = /etc/letsencrypt/live/geiglobal.org/chain.pem
fullchain = /etc/letsencrypt/live/geiglobal.org/fullchain.pem
[renewalparams]
account = f03627682d7ba4e10939c9d515589afa
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
