services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: gei-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-gei}
      POSTGRES_USER: ${POSTGRES_USER:-geiuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-geipassword}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-geiuser} -d ${POSTGRES_DB:-gei}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # GEI Website Application
  app:
    build: .
    container_name: gei-website
    ports:
      - "5000:5000"
      - "5555:5555"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5000}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-geiuser}:${POSTGRES_PASSWORD:-geipassword}@db:5432/${POSTGRES_DB:-gei}?schema=public
      - JWT_SECRET=${JWT_SECRET:-Qw3rty!9zXcVbN7mLpOiUjK1hGfDsA4eR}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - UPLOAD_DIR=${UPLOAD_DIR:-/app/uploads}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-15728640}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
      - DOMAIN=${DOMAIN:-http://localhost:5000}
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5000/api}
      - SEED_DATABASE=${SEED_DATABASE:-true}
      
      # SMTP settings for contact form
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_SECURE=${SMTP_SECURE:-false}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM:-${SMTP_USER}}
      - CONTACT_RECEIVER=${CONTACT_RECEIVER:-${SMTP_USER}}
      
      # Security
      - SESSION_SECRET=${SESSION_SECRET:-your-session-secret-here}
    volumes:
      - uploads_data:/app/uploads
      - ./prisma:/app/prisma
      - ./logs:/app/backend/logs
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
  uploads_data: 